### ISSUE TITLE
Update go-libp2p  and go-libp2p-kad-dht to latest versions

### ISSUE THREAD

**Issue by lidel** [probe-lab/parsec#11]
https://github.com/probe-lab/network-measurements/blob/main/reports/2024/calendar-week-38/ipfs/README.md#dht-performance states that

> The peers run go-libp2p-kad-dht version v0.21.1 + default configurations.

but `go.mod` uses go-libp2p v0.30.0. A bug  / hardcoded string in markdown generator?

Anyway, feels like we should update to latest version. 

There have been some breaking changes, thought i'll fill issue here with a brain dump to save time when someone attemps to update this project to latest go-libp2p and go-libp2p-kad-dht.

Main one is breaking change in [go-libp2p v0.34](https://github.com/libp2p/go-libp2p/releases/tag/v0.34.0) ([go-libp2p-kad-dht v0.26.1](https://github.com/libp2p/go-libp2p-kad-dht/releases/tag/v0.26.1) has fix that makes it compatible), and tldr is marked with 👉️:

> ### Transient Connections are now called Limited Connections
> - Connections to peers over relayed or other limited connections, previously called `transient` are now called `limited` throughout the code. Limited is more descriptive of the connection's behavior and it avoids conflict with Resource Manager's Transient scope.  
> - For Connections, the `Transient` connection state has been renamed to `Limited`. **This is a breaking change** and you'll have to replace uses of `conn.Stat().Transient` with `conn.Stat().Limited`
> - Network context functions like `network.WithUseTransient` are deprecated, use their limited alternatives like `network.WithUseLimited`.
> 
> ### Limited Connectedness state
> - Peers connected to the host via relayed or any other limited connection now report their connectivity state as `Limited`.
> - This state is also reflected in `EvtPeerConnectednessChanged` event. Consumers only interested in peers connected over Unlimited connections can ignore events with Limited Connectedness. **NOTE:** This changes the behavior of the `Connected` Connectedness state. Previously it included all limited connections and now it doesn't. 
> 
> 👉️ To keep existing behavior in your code you can replace checks `connectedness == network.Connected` with `connectedness != network.NotConnected`

**Comment by guillaumemichel** [comment]
> > The peers run go-libp2p-kad-dht version v0.21.1 + default configurations.
> 
> but `go.mod` uses go-libp2p v0.30.0. A bug / hardcoded string in markdown generator?

I realize now that `go-libp2p-kad-dht` isn't a go dependency, but it was [**copied**](https://github.com/probe-lab/parsec/tree/main/go-libp2p-kad-dht) (not even git submodule) to `parsec`. Which is why the dependency version is hardcoded...

I will update it, and make a proper git submodule for `go-libp2p-kad-dht` so that `parsec` can catch up with the latest versions easily.

Thanks for raising this @lidel
